/*potions*/
create table
  public.potions (
    potion_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_potions integer null,
    sku text null,
    price integer null,
    name text null,
    type integer[] null,
    constraint global_inventory_duplicate_pkey primary key (potion_id)
  ) tablespace pg_default;

  /*carts*/
create table
  public.carts (
    cart_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer text null,
    constraint Carts_pkey primary key (cart_id)
  ) tablespace pg_default;

  /*cart_items*/
create table
  public.cart_items (
    cart_items_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id bigint null,
    potion_id bigint null,
    quantity integer null,
    constraint cart_items_pkey primary key (cart_items_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potions (potion_id)
  ) tablespace pg_default;

  /*gold ledger*/
  create table
  public.gold_ledger (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    change integer null,
    transaction_id bigint null,
    constraint gold_ledger_pkey primary key (id),
    constraint gold_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (transaction_id)
  ) tablespace pg_default;

  /*ml ledger*/
  create table
  public.ml_ledger (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    transaction_id bigint null,
    red_ml_change integer null,
    green_ml_change integer null,
    blue_ml_change integer null,
    dark_ml_change integer null default 0,
    constraint ledger_pkey primary key (id),
    constraint ml_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (transaction_id)
  ) tablespace pg_default;

  /*potion ledger*/
  create table
  public.potion_ledger (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    change integer null,
    transaction_id bigint null,
    potion_id bigint null,
    constraint potion_ledger_pkey primary key (id),
    constraint potion_ledger_potion_id_fkey foreign key (potion_id) references potions (potion_id),
    constraint potion_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (transaction_id)
  ) tablespace pg_default;

  /*transaction*/
  create table
  public.transactions (
    transaction_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text null,
    constraint transactions_pkey primary key (transaction_id)
  ) tablespace pg_default;