/*potions*/
create table
  public.potions (
    potion_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_potions integer null,
    red_ml integer null,
    green_ml integer null,
    blue_ml integer null,
    dark integer null,
    sku text null,
    price integer null,
    name text null,
    constraint global_inventory_duplicate_pkey primary key (potion_id)
  ) tablespace pg_default;

  /*carts*/
create table
  public.carts (
    cart_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer text null,
    constraint Carts_pkey primary key (cart_id)
  ) tablespace pg_default;

  /*cart_items*/
create table
  public.cart_items (
    cart_items_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id bigint null,
    potion_id bigint null,
    quantity integer null,
    constraint cart_items_pkey primary key (cart_items_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potions (potion_id)
  ) tablespace pg_default;

  /*global_inventory: FIX THE NAME*/
  create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_red_ml integer null,
    gold integer null,
    num_green_ml integer null,
    num_blue_ml integer null,
    constraint global_inventory_duplicate_pkey1 primary key (id)
  ) tablespace pg_default;